<div class="relative inline-block mt-[10px] max-sm:[&_.media-popup]:bottom-auto max-sm:[&_.media-popup]:top-[calc(100%+8px)]">
  <button class="w-[22px] h-[22px] rounded-full border border-border text-muted text-[15px] leading-none flex items-center justify-center transition-[border-color,color] duration-150 cursor-pointer hover:border-subtle hover:text-subtle" type="button" title="Añadir media">+</button>
  <div class="media-popup hidden absolute bottom-[calc(100%+8px)] left-0 bg-white border border-border rounded-xl p-[5px] min-w-[148px] z-[100] shadow-[0_8px_24px_rgba(0,0,0,0.07)]">
    <button class="flex items-center gap-[9px] py-2 px-[10px] rounded-md text-sm text-fg cursor-pointer transition-[background] duration-100 w-full text-left hover:bg-hover" type="button" data-type="image"    data-accept="image/*"><span class="text-sm w-[18px] text-center shrink-0">🖼</span>Imagen</button>
    <button class="flex items-center gap-[9px] py-2 px-[10px] rounded-md text-sm text-fg cursor-pointer transition-[background] duration-100 w-full text-left hover:bg-hover" type="button" data-type="audio"    data-accept="audio/*"><span class="text-sm w-[18px] text-center shrink-0">🎵</span>Audio</button>
    <button class="flex items-center gap-[9px] py-2 px-[10px] rounded-md text-sm text-fg cursor-pointer transition-[background] duration-100 w-full text-left hover:bg-hover" type="button" data-type="video"    data-accept="video/*"><span class="text-sm w-[18px] text-center shrink-0">🎬</span>Video</button>
    <button class="flex items-center gap-[9px] py-2 px-[10px] rounded-md text-sm text-fg cursor-pointer transition-[background] duration-100 w-full text-left hover:bg-hover" type="button" data-type="document" data-accept="*/*"><span class="text-sm w-[18px] text-center shrink-0">📄</span>Documento</button>
  </div>
</div>
